version: "3.9"

services:
  cockroach:
    image: cockroachdb/cockroach
    ports:
     - "26257:26257"
    command: start-single-node --insecure
    volumes:
     - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"